name: build-test
run-name: Build & test the project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Create test k8s Kind Cluster (kind-kind)
        uses: helm/kind-action@v1.4.0
        with:
          config: kubereflex/kind-config.yaml
          cluster_name: kind-test

      - name: Create test k8s Kind Cluster (kind-kind2)
        uses: helm/kind-action@v1.4.0
        with:
          config: kubereflex/kind2-config.yaml
          cluster_name: kind-test2
          
      - name: Test
        run: go test -v ./...

      - name: Create k8s Kind Cluster (kind-kind)
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kubereflex/kind-config.yaml

      - name: Create k8s Kind Cluster (kind-kind2)
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kubereflex/kind2-config.yaml

      - name: Run example install
        run: go test -v ./... install -r default_active_resource.yaml -R default_passive_resource.yaml -a -v

      - name: Run example uninstall
        run: go test -v ./... uninstall -r default_active_resource.yaml -R default_passive_resource.yaml -d