name: build-test
run-name: Build with updated dependencies
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install dependencies
        run: go get -u .

      - name: Build
        run: go build -v ./...