name: build-test-updated
run-name: Build with updated dependencies
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          check-latest: true

      - name: Install dependencies
        run: go get -u .

      - name: Build
        run: go build -v ./...